version: '3.8'

services:
  db:                   # db host fromm django settings.py
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespass

  redis:
    image: redis:5
    ports:
      - "6379:6379"

  webapp:       # web application name
    build: .
    command: gunicorn djangoProject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/django
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:1.19.0
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - webapp

  celery-worker:
    build: .
    command: celery --app djangoProject worker
    depends_on:
      - db
      - webapp
      - redis

  celery-beat:
    build: .
    command: celery --app djangoProject beat
    depends_on:
      - db
      - webapp
      - redis

volumes:
  postgres_data: