version: "3.8"

services:
  flask_app:
    build: "."
    command: gunicorn --bind 0.0.0.0:4200 app:app
    restart: always
    ports:
      - "4200:4200"
    environment:
      - DB_TYPE=postgresql
      - DB_USER=postgresuser
      - DB_PASSWORD=postgrespass
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=flaskdb
    depends_on:
      - database

  database:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_DB=flaskdb
    ports:
      - "5432:5432"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - flask_app

volumes:
  postgres_data:
